CREATE TABLE rol(
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL  
);

CREATE TABLE usuario(
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol BIGINT NOT NULL REFERENCES rol(id),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ciudad(
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE jugueteria(
    id BIGSERIAL PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    ruc VARCHAR(255) NOT NULL,
    titular VARCHAR(255) NOT NULL,
    ciudad BIGINT NOT NULL REFERENCES ciudad(id),
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fabricante(
    id BIGSERIAL PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    cedula VARCHAR(255) NOT NULL,
    correo VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE juguete(
    id BIGSERIAL PRIMARY KEY,
    id_jugueteria BIGINT NOT NULL REFERENCES jugueteria(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    stock INTEGER NOT NULL,
    imagen VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orden(
    id BIGSERIAL PRIMARY KEY,
    id_juguete BIGINT NOT NULL REFERENCES juguete(id) ON DELETE CASCADE,
    id_fabricante BIGINT NOT NULL REFERENCES fabricante(id) ON DELETE CASCADE,
    cantidad INTEGER NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);